from pydantic import BaseModel
from typing import Optional


class VehicleBase(BaseModel):
    make: str
    model: str
    year: int


class VehicleCreate(VehicleBase):
    pass  # Add any additional fields needed for creation


class Vehicle(VehicleBase):
    id: int  # Assuming the ID is generated by the database

    class Config:
        orm_mode = True  # This allows compatibility with ORM models
